<template><h2 id="前提" tabindex="-1"><a class="header-anchor" href="#前提" aria-hidden="true">#</a> 前提</h2>
<p>我们修改了语言为中文后，平台游戏都有对应的游戏列表可以更改成中文，但是这个系统的设置菜单SETUP却无法修改，其实也是可以的。正好也可以顺便解决国内小伙伴<RouterLink to="/more/04.install_drastic.html">安装NDS模拟器drastic</RouterLink>失败的问题。</p>
<h2 id="修改setup菜单路径" tabindex="-1"><a class="header-anchor" href="#修改setup菜单路径" aria-hidden="true">#</a> 修改SETUP菜单路径</h2>
<p>把SETUP菜单的路径修改成<code>/storage/roms/setup</code>，并将原SETUP菜单路径下内容复制到<code>/storage/roms/setup</code>，执行以下命令：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">sed</span> -i <span class="token string">'s/\/usr\/bin\/scripts\/setup/\/storage\/roms\/setup/g'</span> /storage/.config/emulationstation/es_systems.cfg
<span class="token function">cp</span> -r /usr/bin/scripts/setup/ /storage/roms/
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p><img src="@source/more/assets/more_3-1.png" alt="more_3-1.png" loading="lazy"></p>
<p>上面的命令，就是修改<code>es_systems.cfg</code>文件的内容和复制SETUP菜单内容。</p>
<h2 id="补全setup菜单图片" tabindex="-1"><a class="header-anchor" href="#补全setup菜单图片" aria-hidden="true">#</a> 补全SETUP菜单图片</h2>
<p>上面两条命令完成后，原版的SETUP菜单下的几个选项（youtube、bluetooth、scummvm）没有图片，那么我们自己补几张图片，将下列3张图片放到<code>/storage/roms/setup/downloaded_images</code>目录下，就补全了SETUP菜单图片。（图片下载到本站的【资源下载】➡【工具】）</p>
<ul>
<li><code>youtube.png</code></li>
<li><code>bluetooth.png</code></li>
<li><code>scummvm.png</code></li>
</ul>
<p><img src="@source/more/assets/more_3-2.png" alt="more_3-2.png" loading="lazy"></p>
<h2 id="修改setup菜单为中文" tabindex="-1"><a class="header-anchor" href="#修改setup菜单为中文" aria-hidden="true">#</a> 修改SETUP菜单为中文</h2>
<p>打开<code>/storage/roms/setup/gamelist.xml</code>，可以将<u><strong>名字</strong></u>和<u><strong>描述</strong></u>修改为中文（即name标签和desc标签，需要自己翻译修改），然后保存。</p>
<p><img src="@source/more/assets/more_3-3.png" alt="more_3-3.png" loading="lazy"></p>
<p>重启EmulationStation再进入SETUP菜单看看，已经修改成中文了。</p>
<p><img src="@source/more/assets/more_3-4.png" alt="more_3-4.png" loading="lazy"></p>
<h2 id="ports游戏平台" tabindex="-1"><a class="header-anchor" href="#ports游戏平台" aria-hidden="true">#</a> PORTS游戏平台</h2>
<p>当然，还有系统自带的ports游戏平台，也是可以修改的。根据<code>es_systems.cfg</code>文件里ports平台的相关信息，打开<code>/storage/roms/ports_scripts/gamelist.xml</code>，进行翻译修改成中文即可。</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code>    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>system</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>name</span><span class="token punctuation">></span></span>ports<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>name</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>fullname</span><span class="token punctuation">></span></span>Ports<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>fullname</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>manufacturer</span><span class="token punctuation">></span></span>Ports<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>manufacturer</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>release</span><span class="token punctuation">></span></span>Varies<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>release</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>hardware</span><span class="token punctuation">></span></span>port<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>hardware</span><span class="token punctuation">></span></span>            
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>path</span><span class="token punctuation">></span></span>/storage/roms/ports_scripts<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>path</span><span class="token punctuation">></span></span>    <span class="token comment">&lt;!--ports平台路径--></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>extension</span><span class="token punctuation">></span></span>.sh .SH<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>extension</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>command</span><span class="token punctuation">></span></span>/usr/bin/bash %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers="%CONTROLLERSCONFIG%"<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>command</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>platform</span><span class="token punctuation">></span></span>ports<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>platform</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>theme</span><span class="token punctuation">></span></span>ports<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>theme</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>system</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><div class="custom-container tip"><p class="custom-container-title">关于es_systems.cfg文件</p>
<p><code>es_systems.cfg</code>文件：全路径名称为<code>/storage/.config/emulationstation/es_systems.cfg</code>。</p>
<p>它是EmuELEC系统的前端EmulationStation（后面简称ES）的平台配置文件，也就是我们看到的游戏平台的分类及相关配置都在这个文件里。比如NEOGEO平台的配置内容：</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code>    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>system</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>name</span><span class="token punctuation">></span></span>neogeo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>name</span><span class="token punctuation">></span></span>                            <span class="token comment">&lt;!--平台名称--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>fullname</span><span class="token punctuation">></span></span>SNK Neo-Geo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>fullname</span><span class="token punctuation">></span></span>            <span class="token comment">&lt;!--平台全称--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>manufacturer</span><span class="token punctuation">></span></span>SNK<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>manufacturer</span><span class="token punctuation">></span></span>            <span class="token comment">&lt;!--平台开发商--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>release</span><span class="token punctuation">></span></span>1990<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>release</span><span class="token punctuation">></span></span>                        <span class="token comment">&lt;!--平台发行年份--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>hardware</span><span class="token punctuation">></span></span>console<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>hardware</span><span class="token punctuation">></span></span>                <span class="token comment">&lt;!--平台控制器--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>path</span><span class="token punctuation">></span></span>/storage/roms/neogeo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>path</span><span class="token punctuation">></span></span>            <span class="token comment">&lt;!--平台游戏存放路径--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>extension</span><span class="token punctuation">></span></span>.7z .7Z .zip .ZIP<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>extension</span><span class="token punctuation">></span></span>    <span class="token comment">&lt;!--平台游戏ROM扩展名--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>command</span><span class="token punctuation">></span></span>emuelecRunEmu.sh %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers="%CONTROLLERSCONFIG%"<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>command</span><span class="token punctuation">></span></span>        <span class="token comment">&lt;!--调用命令emuelecRunEmu.sh运行游戏--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>platform</span><span class="token punctuation">></span></span>neogeo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>platform</span><span class="token punctuation">></span></span>                    <span class="token comment">&lt;!--平台--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>theme</span><span class="token punctuation">></span></span>neogeo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>theme</span><span class="token punctuation">></span></span>                        <span class="token comment">&lt;!--主题--></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>emulators</span><span class="token punctuation">></span></span>                                    <span class="token comment">&lt;!--模拟器相关--></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>emulator</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>libretro<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>                <span class="token comment">&lt;!--模拟器--></span>
                <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>cores</span><span class="token punctuation">></span></span>                                    <span class="token comment">&lt;!--模拟器核心相关--></span>
                    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>core</span> <span class="token attr-name">default</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>true<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>fbneo<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>core</span><span class="token punctuation">></span></span>    <span class="token comment">&lt;!--模拟器默认核心--></span>
                    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>core</span><span class="token punctuation">></span></span>mame2003_plus<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>core</span><span class="token punctuation">></span></span>            <span class="token comment">&lt;!--模拟器其它核心--></span>
                    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>core</span><span class="token punctuation">></span></span>fbalpha2012<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>core</span><span class="token punctuation">></span></span>            <span class="token comment">&lt;!--模拟器其它核心--></span>
                    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>cores</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>emulator</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>emulators</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>system</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br></div></div><p>如需修改相关内容，如添加模拟器核心、修改默认模拟器核心等，按照正确格式修改</p>
</div>
</template>
